layout_spectrum: 0.7166948
color:
  saturation: 0.9093332
  brandStrength: 0.5952783
  lightness: 0.564081
  brandColors:
    - '#1A1919'
    - '#F4E8C6'
    - '#6D6B6C'
    - '#BBAC81'
    - '#20135E'
  rhythmicContrast: 0.5529907
typography_spectrum: 0.2048904
name: First Time Dad
